run:

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  modules-download-mode: readonly

linters:
  enable:
    - staticcheck
    - exportloopref
    - dupl
    - govet
    - funlen
    - gocritic
    - goconst
    - tenv
    - ineffassign
    - bodyclose
    - gosec
    - prealloc
    - unused
    - gofmt
    - revive
    - stylecheck
    - whitespace
    - goprintffuncname
    - gosimple
    - gocyclo

output:
  format: colored-line-number
