name: Test Go

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'
    paths:
      - '**.go'
      - .github/workflows/go.yml
      - "go.mod"
      - "go.sum"


jobs:
  test:
    permissions:
        security-events: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.18', '1.19']
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Test
      run: make test

    - name: Benchmark
      run: make bench

    - name: Coverage to Deepsource
      if: ${{ runner.os == 'Linux' && env.DEEPSOURCE_DSN != null }}
      run: |
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key go --value-file c.out
      env: 
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      
    - uses: codecov/codecov-action@v3
      with:
        files: c.out
        fail_ci_if_error: true
