name: Test Go

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'
    paths:
      - '**.go'
      - .github/workflows/go.yml


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.16', '1.15', '1.14', '1.13' ]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v2.1.6
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        cd go
        go vet .
        golint -set_exit_status 
    
    - name: Test
      run: |
        cd go
        go test -race -v -coverprofile="c.out"
        go tool cover -func="c.out"

    - name: Gosec Security Scanner
      run: |
        go get -u github.com/securego/gosec/v2/cmd/gosec
        cd go
        gosec -no-fail -fmt sarif -out results.sarif ./...
